### ISSUE TITLE
MissingLibraryException: Could not find 'libseon.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].

### ISSUE THREAD

**Issue by sstarkov-fhl** [seontechnologies/seon-android-sdk-public#27]
Hi!
We've recently integrated the version 6.0.2 of this SDK.
And now we are facing some rare crashes in production.
It affects < 0.1% of users.

<details>

  <summary>Crash stacktrace</summary>

  ```
Caused by com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libseon.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:175)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
       at io.seon.androidsdk.service.JNIHandler.loadLibrary(JNIHandler.java:26)
       at io.seon.androidsdk.service.SeonEncrypt.<init>(SourceFile:26)
       at io.seon.androidsdk.service.HardwareProbe.bootstrap(HardwareProbe.java:15)
       at io.seon.androidsdk.service.Probes.a(Probes.java:15)
       at io.seon.androidsdk.service.SeonImpl.<init>(SeonImpl.java:15)
       at io.seon.androidsdk.service.SeonBuilder.build(SeonBuilder.java:985)
       at xxx.SeonInitializerImpl.init(SeonInitializerImpl.java:35)
       at xxx.MainActivity.initSdks(MainActivity.kt:241)
       at xxx.MainActivity.onCreate(MainActivity.kt:138)
  ```

</details>
We have different variations of it:
<br />
1. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: []. (majority of cases)
<br />
2. Looked for: [x86_64, x86, arm64-v8a, armeabi-v7a, armeabi], but only found: []. (Nexus 5X, android 11)
<br />
3. Looked for: [x86], but only found: []. (Nexus 5X, android 8.1.0)

Devices for the first variation:
Vivo Y17s, android 13
Vivo Y27, android 13
Vivo Y02t, android 13
Oppo A17, android 12
Oppo A58, android 13
Pixel 3 XL, android 9
Xiaomi Redmi 13C, android 13
Honor X5 Plus, android 13
Oppo CPH2349, android 11

None of the devices is rooted according to Crashlytics.

It seems to be a [ReLinker](https://github.com/KeepSafe/ReLinker) issue.
But maybe you know the nature of it?
Any idea what could cause this?
Nexus 5X with x86 looks like an emulator.

Thanks in advance!

**Comment by robertorsulics-seon** [comment]
We could not reproduce
