### ISSUE TITLE
Error when trying to get fingerprint on Android Emulator

### ISSUE THREAD

**Issue by DjordjeMancic97** [seontechnologies/seon-android-sdk-public#7]
When I use the SDK on real device it works but when I run it on Android Emulator I see errors and after some time app crashes.

```
W/pool-53-thread-(13819): type=1400 audit(0.0:385): avc: denied { nlmsg_readpriv } for scontext=u:r:untrusted_app:s0:c245,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c245,c256,c512,c768 tclass=netlink_route_socket permissive=0 bug=b/155595000 app=de.bank.clanq
W/pool-53-thread-(13819): type=1400 audit(0.0:386): avc: denied { nlmsg_readpriv } for scontext=u:r:untrusted_app:s0:c245,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c245,c256,c512,c768 tclass=netlink_route_socket permissive=0 bug=b/155595000 app=de.bank.clanq
D/CompatibilityChangeReporter(13819): Compat change id reported: 170188668; UID 10245; state: ENABLED
E/io.seon.androidsdk.service.TelephonyProbe(13819): There is no granted READ_PHONE_STATE permission
W/de.bank.clanq(13819): Accessing hidden method Lcom/android/internal/os/PowerProfile;-><init>(Landroid/content/Context;)V (unsupported, reflection, allowed)
W/de.bank.clanq(13819): Accessing hidden method Lcom/android/internal/os/PowerProfile;->getBatteryCapacity()D (unsupported, reflection, allowed)
D/io.seon.androidsdk.service.DynamicComponentTask(13819): javax.net.ssl.SSLHandshakeException: Chain validation failed
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at io.seon.androidsdk.service.DynamicComponentTask.a(Unknown Source:165)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at io.seon.androidsdk.service.DynamicComponentTask.doInBackground(Unknown Source:2)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at android.os.AsyncTask$3.call(AsyncTask.java:394)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at java.lang.Thread.run(Thread.java:920)
D/io.seon.androidsdk.service.DynamicComponentTask(13819): Caused by: java.security.cert.CertificateException: Chain validation failed
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:720)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:550)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:571)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:616)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:616)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:616)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:506)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:426)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       ... 28 more
D/io.seon.androidsdk.service.DynamicComponentTask(13819): Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:716)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       ... 45 more
D/io.seon.androidsdk.service.DynamicComponentTask(13819): Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:619)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       ... 50 more
D/io.seon.androidsdk.service.DynamicComponentTask(13819):       Suppressed: java.security.cert.CertPathValidatorException: Could not determine revocation status
D/io.seon.androidsdk.service.DynamicComponentTask(13819):               at sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1092)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):               at sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:910)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):               at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:577)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):               at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):               at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
D/io.seon.androidsdk.service.DynamicComponentTask(13819):               ... 52 more
I/DrmUtils(13819): found android.hardware.drm@1.0::IDrmFactory clearkey
I/DrmUtils(13819): found android.hardware.drm@1.0::IDrmFactory default
I/DrmUtils(13819): found android.hardware.drm@1.0::IDrmFactory widevine
I/DrmUtils(13819): found android.hardware.drm@1.1::IDrmFactory clearkey
I/DrmUtils(13819): found android.hardware.drm@1.1::IDrmFactory widevine
I/DrmUtils(13819): found android.hardware.drm@1.2::IDrmFactory clearkey
I/DrmUtils(13819): found android.hardware.drm@1.2::IDrmFactory widevine
I/DrmUtils(13819): found android.hardware.drm@1.3::IDrmFactory clearkey
I/DrmUtils(13819): found android.hardware.drm@1.3::IDrmFactory widevine
E/io.seon.androidsdk.service.SeonFingerprint(13819): android.media.MediaDrmResetException: mediaserver died
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at android.media.MediaDrm.getPropertyByteArray(Native Method)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.MediaProbe.b(Unknown Source:29)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.DeviceHasher.a(Unknown Source:5)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.SeonFingerprint.d(Unknown Source:473)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:0)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:2)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.SeonFingerprint.$r8$lambda$7shO_kdi5Jed2lCT9AiGYlkeTlI(Unknown Source:0)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.SeonFingerprint$$ExternalSyntheticLambda1.run(Unknown Source:8)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at java.lang.Thread.run(Thread.java:920)
E/io.seon.androidsdk.service.SeonFingerprint(13819): android.media.MediaDrmResetException: mediaserver died
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at android.media.MediaDrm.getPropertyByteArray(Native Method)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.MediaProbe.b(Unknown Source:29)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.DeviceHasher.a(Unknown Source:5)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.SeonFingerprint.d(Unknown Source:473)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:0)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:2)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.SeonFingerprint.$r8$lambda$7shO_kdi5Jed2lCT9AiGYlkeTlI(Unknown Source:0)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at io.seon.androidsdk.service.SeonFingerprint$$ExternalSyntheticLambda1.run(Unknown Source:8)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/io.seon.androidsdk.service.SeonFingerprint(13819):    at java.lang.Thread.run(Thread.java:920)
W/System.err(13819): io.seon.androidsdk.exception.SeonException: Fingerprint could not be generated
W/System.err(13819):    at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:14)
W/System.err(13819):    at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:2)
W/System.err(13819):    at io.seon.androidsdk.service.SeonFingerprint.$r8$lambda$7shO_kdi5Jed2lCT9AiGYlkeTlI(Unknown Source:0)
W/System.err(13819):    at io.seon.androidsdk.service.SeonFingerprint$$ExternalSyntheticLambda1.run(Unknown Source:8)
W/System.err(13819):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err(13819):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(13819):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(13819):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(13819):    at java.lang.Thread.run(Thread.java:920)

```

**Comment by robertorsulics-seon** [comment]
Hi @DjordjeMancic97 ! Please try to reset the emulator and try again.

**Comment by DjordjeMancic97** [comment]
> Hi @DjordjeMancic97 ! Please try to reset the emulator and try again.

Thanks for response, I was not able to make it work on my current emulator but it works for my colleague so I will close this issue.
