### ISSUE TITLE
W/System.err(10807): org.json.JSONException: No value for manufacturer

### ISSUE THREAD

**Issue by Shahin-Sefidgaran** [seontechnologies/seon-android-sdk-public#9]
Hello
I am receiving the SeonFingerprint however, I also receive some exceptions before that i would like to know what are they about?
```
Launching lib\main.dart on Redmi Note 9S in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:12388/hvHlL9GHis8=/ws
W/System.err(20233): org.json.JSONException: No value for manufacturer
W/System.err(20233): 	at org.json.JSONObject.get(JSONObject.java:399)
W/System.err(20233): 	at org.json.JSONObject.getString(JSONObject.java:560)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName$DeviceInfo.<init>(DeviceName.java:374)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName$DeviceInfo.<init>(DeviceName.java:347)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName.getDeviceInfo(DeviceName.java:186)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName.getDeviceName(DeviceName.java:138)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName.getDeviceName(DeviceName.java:111)
W/System.err(20233): 	at io.seon.androidsdk.service.DeviceProbe.c(Unknown Source:5)
W/System.err(20233): 	at io.seon.androidsdk.service.DeviceProbe.$r8$lambda$Xu6jlTbpk5fkvE152aHCxdYuHGc(Unknown Source:0)
W/System.err(20233): 	at io.seon.androidsdk.service.DeviceProbe$$ExternalSyntheticLambda6.a(Unknown Source:2)
W/System.err(20233): 	at io.seon.androidsdk.service.AbstractSeonProbe.a(Unknown Source:0)
W/System.err(20233): 	at io.seon.androidsdk.service.DeviceProbe.q(Unknown Source:24)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.d(Unknown Source:20)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:0)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:2)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.$r8$lambda$7shO_kdi5Jed2lCT9AiGYlkeTlI(Unknown Source:0)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint$$ExternalSyntheticLambda1.run(Unknown Source:8)
W/System.err(20233): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err(20233): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(20233): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(20233): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(20233): 	at java.lang.Thread.run(Thread.java:919)
D/AudioManager(20233): getStreamVolume isRestricted mode = 0
I/chatty  (20233): uid=10348(com.example.seon_plugin_example) pool-1-thread-1 identical 2 lines
D/AudioManager(20233): getStreamVolume isRestricted mode = 0
E/io.seon.androidsdk.service.TelephonyProbe(20233): There is no granted READ_PHONE_STATE permission
E/io.seon.androidsdk.service.TelephonyProbe(20233): There is no granted READ_PHONE_STATE permission
W/System.err(20233): org.json.JSONException: No value for manufacturer
W/System.err(20233): 	at org.json.JSONObject.get(JSONObject.java:399)
W/System.err(20233): 	at org.json.JSONObject.getString(JSONObject.java:560)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName$DeviceInfo.<init>(DeviceName.java:374)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName$DeviceInfo.<init>(DeviceName.java:347)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName.getDeviceInfo(DeviceName.java:186)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName.getDeviceName(DeviceName.java:138)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName.getDeviceName(DeviceName.java:111)
W/System.err(20233): 	at io.seon.androidsdk.service.DeviceProbe.c(Unknown Source:5)
W/System.err(20233): 	at io.seon.androidsdk.service.DeviceProbe.b(Unknown Source:5)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:37)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.d(Unknown Source:383)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:0)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:2)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.$r8$lambda$7shO_kdi5Jed2lCT9AiGYlkeTlI(Unknown Source:0)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint$$ExternalSyntheticLambda1.run(Unknown Source:8)
W/System.err(20233): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err(20233): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(20233): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(20233): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(20233): 	at java.lang.Thread.run(Thread.java:919)
W/System.err(20233): org.json.JSONException: No value for manufacturer
W/System.err(20233): 	at org.json.JSONObject.get(JSONObject.java:399)
W/System.err(20233): 	at org.json.JSONObject.getString(JSONObject.java:560)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName$DeviceInfo.<init>(DeviceName.java:374)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName$DeviceInfo.<init>(DeviceName.java:347)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName.getDeviceInfo(DeviceName.java:186)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName.getDeviceInfo(DeviceName.java:152)
W/System.err(20233): 	at io.seon.androidsdk.service.DeviceProbe.b(Unknown Source:14)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:37)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.d(Unknown Source:383)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:0)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:2)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.$r8$lambda$7shO_kdi5Jed2lCT9AiGYlkeTlI(Unknown Source:0)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint$$ExternalSyntheticLambda1.run(Unknown Source:8)
W/System.err(20233): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err(20233): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(20233): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(20233): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(20233): 	at java.lang.Thread.run(Thread.java:919)
W/System.err(20233): org.json.JSONException: No value for manufacturer
W/System.err(20233): 	at org.json.JSONObject.get(JSONObject.java:399)
W/System.err(20233): 	at org.json.JSONObject.getString(JSONObject.java:560)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName$DeviceInfo.<init>(DeviceName.java:374)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName$DeviceInfo.<init>(DeviceName.java:347)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName.getDeviceInfo(DeviceName.java:186)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName.getDeviceInfo(DeviceName.java:152)
W/System.err(20233): 	at io.seon.androidsdk.service.DeviceProbe.b(Unknown Source:25)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:37)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.d(Unknown Source:383)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:0)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:2)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.$r8$lambda$7shO_kdi5Jed2lCT9AiGYlkeTlI(Unknown Source:0)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint$$ExternalSyntheticLambda1.run(Unknown Source:8)
W/System.err(20233): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err(20233): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(20233): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(20233): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(20233): 	at java.lang.Thread.run(Thread.java:919)
W/System.err(20233): org.json.JSONException: No value for manufacturer
W/System.err(20233): 	at org.json.JSONObject.get(JSONObject.java:399)
W/System.err(20233): 	at org.json.JSONObject.getString(JSONObject.java:560)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName$DeviceInfo.<init>(DeviceName.java:374)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName$DeviceInfo.<init>(DeviceName.java:347)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName.getDeviceInfo(DeviceName.java:186)
W/System.err(20233): 	at com.jaredrummler.android.device.DeviceName.getDeviceInfo(DeviceName.java:152)
W/System.err(20233): 	at io.seon.androidsdk.service.DeviceProbe.b(Unknown Source:36)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:37)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.d(Unknown Source:383)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:0)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:2)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint.$r8$lambda$7shO_kdi5Jed2lCT9AiGYlkeTlI(Unknown Source:0)
W/System.err(20233): 	at io.seon.androidsdk.service.SeonFingerprint$$ExternalSyntheticLambda1.run(Unknown Source:8)
W/System.err(20233): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err(20233): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(20233): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(20233): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(20233): 	at java.lang.Thread.run(Thread.java:919)
W/_plugin_exampl(20233): Accessing hidden method Lcom/android/internal/os/PowerProfile;-><init>(Landroid/content/Context;)V (greylist, reflection, allowed)
W/_plugin_exampl(20233): Accessing hidden method Lcom/android/internal/os/PowerProfile;->getBatteryCapacity()D (greylist, reflection, allowed)
D/NetworkSecurityConfig(20233): No Network Security Config specified, using platform default
I/DpmTcmClient(20233): RegisterTcmMonitor from: $Proxy0
W/Gralloc3(20233): mapper 3.x is not supported
I/_plugin_exampl(20233): ProcessProfilingInfo new_methods=1264 is saved saved_to_disk=1 resolve_classes_delay=8000
D/io.seon.androidsdk.service.DynamicComponentTask(20233): java.net.SocketTimeoutException: SSL handshake timed out
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at io.seon.androidsdk.service.DynamicComponentTask.a(Unknown Source:162)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at io.seon.androidsdk.service.DynamicComponentTask.doInBackground(Unknown Source:2)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
D/io.seon.androidsdk.service.DynamicComponentTask(20233): 	at java.lang.Thread.run(Thread.java:919)
W/BpBinder(20233): Slow Binder: BpBinder transact took 265 ms, interface=android.drm.IDrm, code=17 oneway=false
```

**Comment by Byczkow** [comment]
Same, also have another warnings (and one error) in log about SQL:

```
E/SQLiteLog: (1) no such table: devices in "SELECT name, codename, model FROM devices WHERE codename LIKE ? OR model LIKE ?"
W/System.err: android.database.sqlite.SQLiteException: no such table: devices (code 1 SQLITE_ERROR): , while compiling: SELECT name, codename, model FROM devices WHERE codename LIKE ? OR model LIKE ?
W/System.err:     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
W/System.err:     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1047)
W/System.err:     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:654)
W/System.err:     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
W/System.err:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
W/System.err:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
W/System.err:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1546)
W/System.err:     at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1393)
W/System.err:     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1264)
W/System.err:     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1432)
W/System.err:     at com.jaredrummler.android.device.DeviceDatabase.queryToDevice(DeviceDatabase.java:116)
W/System.err:     at com.jaredrummler.android.device.DeviceName.getDeviceInfo(DeviceName.java:193)
W/System.err:     at com.jaredrummler.android.device.DeviceName.getDeviceName(DeviceName.java:138)
W/System.err:     at com.jaredrummler.android.device.DeviceName.getDeviceName(DeviceName.java:111)
W/System.err:     at io.seon.androidsdk.service.DeviceProbe.c(Unknown Source:5)
W/System.err:     at io.seon.androidsdk.service.DeviceProbe.$r8$lambda$Xu6jlTbpk5fkvE152aHCxdYuHGc(Unknown Source:0)
W/System.err:     at io.seon.androidsdk.service.DeviceProbe$$ExternalSyntheticLambda5.a(Unknown Source:2)
W/System.err:     at io.seon.androidsdk.service.AbstractSeonProbe.a(Unknown Source:0)
W/System.err:     at io.seon.androidsdk.service.DeviceProbe.q(Unknown Source:24)
W/System.err:     at io.seon.androidsdk.service.SeonFingerprint.d(Unknown Source:20)
W/System.err:     at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:0)
W/System.err:     at io.seon.androidsdk.service.SeonFingerprint.a(Unknown Source:2)
W/System.err:     at io.seon.androidsdk.service.SeonFingerprint.$r8$lambda$7shO_kdi5Jed2lCT9AiGYlkeTlI(Unknown Source:0)
W/System.err:     at io.seon.androidsdk.service.SeonFingerprint$$ExternalSyntheticLambda1.run(Unknown Source:8)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:920)
```

**Comment by Byczkow** [comment]
@robertorsulics-seon
